"""message

Revision ID: c3c24acd5b37
Revises: 7c9db5a4108c
Create Date: 2024-07-11 20:25:59.423875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c24acd5b37'
down_revision = '7c9db5a4108c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
